refactor(action): update misc
enable v3 system target for G14 family
use self-hosted rather than github action server

diff --git a/.github/workflows/auto-update-self-hosted.yml b/.github/workflows/auto-update-self-hosted.yml
--- a/.github/workflows/auto-update-self-hosted.yml
+++ b/.github/workflows/auto-update-self-hosted.yml
@@ -3,8 +3,8 @@ name: "update flakes"
 on:
     # push:
     workflow_dispatch:
-    # schedule:
-    #     - cron: "23 9,23 * * *"
+    schedule:
+        - cron: "23 9,23 * * *"
     # push:
     #   paths:
     #     - ".github/workflows/auto-update.yml"
@@ -16,80 +16,11 @@ permissions:
 
 jobs:
     update-flakes:
-        runs-on: ubuntu-latest
+        runs-on: self-hosted
         env:
-            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             timestamp: "N/A"
         steps:
-            - name: Maximize build space
-              uses: easimon/maximize-build-space@master
-              with:
-                root-reserve-mb: 16384
-                swap-size-mb: 4096
-                build-mount-path: '/nix'
-                remove-dotnet: 'true'
-                remove-android: 'true'
-                remove-haskell: 'true'
-                remove-codeql: 'true'
-                remove-docker-images: 'true'
-
-            - uses: szenius/set-timezone@v2.0
-              with:
-                timezoneLinux: "Asia/Shanghai"
-
             - uses: actions/checkout@v4
-              # with:
-              #   token: ${{ secrets.GITHUB_TOKEN }}
-
-            - name: Install Nix
-              uses: cachix/install-nix-action@v31
-              with:
-                github_access_token: ${{ secrets.GITHUB_TOKEN }}
-                set_as_trusted_user: true
-
-            # - uses: nixbuild/nix-quick-install-action@v32
-            # - name: Restore and save Nix store
-            #   uses: nix-community/cache-nix-action@v6
-            #   with:
-            #     primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
-            #     restore-prefixes-first-match: nix-${{ runner.os }}-
-            #     gc-max-store-size-linux: 5G
-            #     purge: true
-            #     purge-prefixes: nix-${{ runner.os }}-
-            #     purge-created: 0
-            #     purge-last-accessed: 0
-            #     purge-primary-key: never
-
-            - name: Setup cachix
-              uses: cachix/cachix-action@v16
-              with:
-                name: kurikomoe
-                authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
-
-            # - name: Restore and save Nix store
-            #   uses: nix-community/cache-nix-action@v6
-            #   with:
-            #         # restore and save a cache using this key
-            #         primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
-            #         # if there's no cache hit, restore a cache by this prefix
-            #         restore-prefixes-first-match: nix-${{ runner.os }}-
-            #         # collect garbage until the Nix store size (in bytes) is at most this number
-            #         # before trying to save a new cache
-            #         # 1G = 1073741824
-            #         gc-max-store-size-linux: 2G
-            #         # do purge caches
-            #         purge: true
-            #         # purge all versions of the cache
-            #         purge-prefixes: nix-${{ runner.os }}-
-            #         # created more than this number of seconds ago
-            #         purge-created: 0
-            #         # or, last accessed more than this number of seconds ago
-            #         # relative to the start of the `Post Restore and save Nix store` phase
-            #         purge-last-accessed: 0
-            #         # except any version with the key that is the same as the `primary-key`
-            #         purge-primary-key: never
-
-            # - run: nix profile install nixpkgs#nixStatic
 
             - name: update flake
               id: update-flake
@@ -160,6 +91,9 @@ jobs:
                   echo "commit_body<<EOF" >> $GITHUB_OUTPUT
                   cat /tmp/results.clean.txt >> $GITHUB_OUTPUT
                   echo "EOF" >> $GITHUB_OUTPUT
+
+                  cachix push kurikomoe $PATHS || true
+                  attic push r2 $PATHS || true
                 else
                   echo "✅ No meaningful changes detected ($line_count lines). Skipping commit."
                   echo "changes_detected=false" >> $GITHUB_OUTPUT
@@ -183,8 +117,8 @@ jobs:
                   The following package changes were detected in the system closure:
                   ${{ steps.update-flake.outputs.commit_body }}
 
-            - name: Setup upterm session
-              uses: lhotari/action-upterm@v1
-              if: ${{ failure() }}
-              with:
-                wait-timeout-minutes: 5
+            # - name: Setup upterm session
+            #   uses: lhotari/action-upterm@v1
+            #   if: ${{ failure() }}
+            #   with:
+            #     wait-timeout-minutes: 5
